.npmignore, .travis.yml
chore(travis): add initial travis config
codacy reports and badges will be added later when we check travis is working a expected
=> chore(travis): add initial travis config

README.md
docs(readme): add basic badges
=> docs(readme): add basic badges

.zappr.yaml, CHANGELOG.md, CONTRIBUTING.md, README.md, package.json
Clean names and update links to `hexo-theme-doc`.
Add dependency status badge.
=> docs: Update links and name

README.md
docs: Add dependancy status badge
=> docs: Add dependancy status badge

README.md
docs(README): update environment setup, plus minor changes
=> docs(README): update environment setup, plus minor changes

package.json
add --runInBand flag to speed up jest tests
close #6
=> chore(test-coverage): add runInBand flag

.travis.yml, README.md, package.json
=> chore: Add codacy

README.md
* Add WIP to swagger-to-html
* Add Live Demo to Readme.
=> docs: update swagger to html info, add live demo link

source/index.md, source/usage-and-configuration/swagger-to-html.md
docs: Add beta to swagger-to-html
=> docs: Add beta to swagger to html

README.md, package.json
Update dependencies.
Add npm badge.
=> chore: Update deps and add npm badge

lib/nodejs/swagger-ui/__tests__/index.test.js, lib/nodejs/swagger-ui/index.js, lib/nodejs/swagger-ui/partials/snippet.ejs, plugins/swagger-ui.js
Swagger-ui : Add the possibility to turn on/off "try out2 feature and permalinks
=> feat(swagger-ui): add config, permalinks and ability to turn off api explorer

source/usage-and-configuration/swagger-ui.md
docs(swagger-ui): add configuration
=> docs(swagger-ui): add configuration

lib/nodejs/__tests__/swagger-store.test.js, lib/nodejs/swagger-store.js, lib/nodejs/swagger/__tests__/index.test.js, lib/nodejs/swagger/__tests__/swagger.test.js, lib/nodejs/swagger/decorators/__tests__/host.test.js, lib/nodejs/swagger/decorators/__tests__/index.test.js, lib/nodejs/swagger/decorators/docExclude/__tests__/index.test.js, lib/nodejs/swagger/decorators/docExclude/filters/__tests__/index.test.js, lib/nodejs/swagger/decorators/docExclude/filters/__tests__/operations.test.js, lib/nodejs/swagger/decorators/docExclude/filters/__tests__/parameters.test.js, lib/nodejs/swagger/decorators/docExclude/filters/__tests__/paths.test.js, lib/nodejs/swagger/decorators/docExclude/filters/__tests__/security.test.js, lib/nodejs/swagger/decorators/host.js, lib/nodejs/swagger/swagger.js
Add test cases for following.
* Swagger parser
* Swagger Store
* Decorators
=> chore: Add test cases for decorators

plugins/search.js
=> fix(search): generate index also when hexo deploy

.gitignore, README.md, nightwatch.json, package.json, tests/index.js
chore(e2e): add basic setup and docs
=> chore(e2e): add basic setup and docs

package.json
chore(npm): use https for hexo-theme-doc dep
=> chore(npm): use https for hexo-theme-doc dep

.travis.yml
chore(travis): add travis integration
* install
* generate 
* run e2e tests
* deploy if gh-pages-source build job (...when merge the PR a new site version will be published by travis)
=> chore(travis): add travis integration for gh-pages

.travis.yml
=> chore(travis): run e2e tests

.eslintrc, .travis.yml, package.json, tests/index.js
=> chore(eslint): add eslint in gh-pages source branch

README.md
docs(e2e): add travis CI section
=> docs(e2e): add travis CI section

lib/nodejs/search/generator.js, plugins/search.js
refactor(search): work better when hexo is programmaticaly initialized
=> refactor(search): work better when hexo is programmaticaly initialized

.travis.yml, README.md, package.json
chore(travis): remove artifacts upload
=> chore(travis): remove artifacts upload

.travis.yml
chore(travis): don't cache node_modules 
We want always fresh, updated deps, no matter what! 😄
=> chore(travis): don't cache node_modules

layout/layout.ejs, lib/nodejs/project-partial/__tests__/index.test.js, lib/nodejs/project-partial/index.js, plugins/project-partial.js, scripts/all.js
feat(project-partial): add new feature 
close #25
=> feat(project-partial): add new feature

.eslintrc, .gitignore, nightwatch.json, tests/index.js
Add e2e tests for minor use cases.
=> chore: Add more e2e test cases for minor scenarios

_config.yml
Add google analytics for tracking usage.
=> chore: Add google analytics

CODE_OF_CONDUCT.md
docs(community): add code of conduct
=> docs(community): add code of conduct

ISSUE_TEMPLATE.md
docs(community): add issue template
=> docs(community): add issue template

.npmignore
=> chore(npm): update .npmignore

tests/pages/swaggerui.js, tests/tests.js
=> test(swagger-ui): update to handle upcoming swagger-ui v3 support

source/_data/navigation.yaml, source/usage-and-configuration/swagger/petstore.yaml, source/usage-and-configuration/swagger/swagger-ui.md
docs(swagger-ui): update after supporting swagger-ui v3
=> docs(swagger-ui): update after supporting swagger-ui v3

source/_data/navigation.yaml, source/usage-and-configuration/project-partials.md, source/usage-and-configuration/sass-styles.md
=> docs(usage): add sass and project partials pages

lib/nodejs/__tests__/swagger-store.test.js, lib/nodejs/swagger-store.js, lib/nodejs/swagger-to-html/index.js, lib/nodejs/swagger/__tests__/swagger-mocks.js, lib/nodejs/swagger/__tests__/swagger.test.js, lib/nodejs/swagger/swagger.js
fix(swagger): Preserve Model/Classes in swagger while applying decorators.
Closes #70
=> fix(swagger): Preserve Model/Classes in swagger while applying decorators.

lib/nodejs/swagger-to-html/modules/controllers/__tests__/responseSample.test.js, lib/nodejs/swagger-to-html/modules/controllers/responseSample.js
fix(swagger_to_html): sample response including mime type
Closes #54
=> fix(swagger_to_html): sample response including mime type

README.md
Adjust readme so users are not confused by development content.
Fix TOC.
=> docs(readme): adjust readme

source/usage-and-configuration/swagger/introduction.md
docs(swagger): add swagger-parser options section
=> docs(swagger): add swagger-parser options section

source/get-started.md
docs(get-started): install from npm registry
=> docs(get-started): install from npm registry

source/usage-and-configuration/sass-styles.md
=> docs(sass): grammar

source/index.md
=> docs: Add package version.

source/usage-and-configuration/swagger/petstore.yaml
=> docs(swagger): add enum type to sample spec

lib/nodejs/swagger-ui/partials/v3/snippet.ejs
=> fix(swagger): swagger-ui v3 download link

.travis.yml, source/usage-and-configuration/navigation.md, tests/pages/home.js, tests/tests.js
Add test case to check whether the expected logo text is displayed.
related to #119
=> test(logo): add logo text test case

.travis.yml
=> chore(travis): remove test:setup

_config.yml, package.json, source/index.md, source/style/doc.scss, source/usage-and-configuration/sass-styles.md, tests/tests.js
~we should probably wait for a new release including #103 to merge this PR~
* no relative imports anymore
* user should update the configuration
related to #101
=> docs(sass): update SASS styles page

package.json
Update the version of `swagger-ui` to fix the issue with circular references in it.
Related to #129
=> fix(swagger-ui): Update version of swagger UI

lib/browser/search/components.jsx
=> fix(search): add accessibiltity label for search button

source/usage-and-configuration/project-partials.md
=> docs(partials): fix example
